version: "3.7"

services:
  back:
    image: pipeline-back:latest
    init: true
    hostname: ${PLBACK_HOSTNAME}
    extra_hosts:
      - "localhost.localdomain:127.0.0.1"
      # - "node00:192.168.71.160"
      - ${SGE_QUEUE_INFO:-node00:192.168.71.160}
    volumes:
      - ../secrets/sibis:/root/.sibis
      - ../secrets/sibis:/home/ncanda/.sibis
      - ../secrets/aws:/home/ncanda/.aws
      - ../secrets/aes:/root/aes
      - ../backend/sibis-init:/sibis-init
      - ../backend/sibis-resources:/sibis-resources
      # - /sibis-software/hivalc-data-integration:/sibis-software/data-integration
      # - /sibis-software/python-packages:/sibis-software/python-packages
      # - /data1:/fs/storage
      # - /data1/share/hivalc_data:/fs/import
      # - /data1/share/hivalc:/fs/analysis
      # - /data1/share/hivalc:/fs/share
      # - /data1/share/hivalc/operations/.sibis-general-config.yml:/home/ncanda/.sibis-general-config.yml:ro
      # - /mnt/svn:/mnt/svn
    environment:
      # - SVC_CRON=1
      - SMTP_SERVER=${SMTP_SERVER:-127.0.0.1}
      - DOCKER_CONTAINER_NAME=${PLBACK_DOCKER_CONTAINER_NAME}
    restart: unless-stopped
    networks:
      default-net:
        aliases: 
          - pipeline-back

networks:
  default-net: